name = "trip-itinerary"
main = ".open-next/server-functions/default/index.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx open-next@latest build"
